### ISSUE TITLE
Add argument --no-option

### ISSUE THREAD

**Issue by SebastianThorn** [irontec/sngrep#25]
Hi,

would be cool if I could set the filter-settings from F7 as an argument,
something like:

sngrep port 5060 --no-options

```
┌────────────────────────────────────────────────┐
│                 Filter options                 │
├────────────────────────────────────────────────┤
│  Enable filters [*]                            │
├────────────────────────────────────────────────┤
│  SIP From:                                     │
│  SIP To:                                       │
│  Source:                                       │
│  Destiny:                                      │
├────────────────────────────────────────────────┤
│  REGISTER   [*]        OPTIONS    [ ]          │
│  INVITE     [*]        PUBLISH    [*]          │
│  SUBSCRIBE  [*]        MESSAGE    [*]          │
│  NOTIFY     [*]                                │
├────────────────────────────────────────────────┤
│          [ Filter ]         [ Cancel ]         │
└────────────────────────────────────────────────┘
```
is this possible to add?

Br
Sebastian Thörn

**Comment by Kaian** [comment]
Hi Sebastian!

 If I understand, you are not interested in SIP dialogs starting with OPTIONS method.
 You can archieve this using configuration file.

    echo "ingore starting OPTIONS" >> ~/.sngreprc

 The problem with --no-options flag is that other people will want to ignore other methods, so I should think in a more general way to filter messages from command line.

**Comment by SebastianThorn** [comment]
First, I understand your point with adding `--no-options`.

Just tried your config addition, but this dont work for me,
do I have to specify the rc-file? (running live as root if that matters)

I more general way might be `--ignore <method>`

Br
Sebastian Thörn

**Comment by Kaian** [comment]
Right now, `sngreprc` file is searched in:
  * Hidden file in user's home dir ($HOME envvar), that should be `/root/.sngreprc` in your case
  * `/etc/sngreprc`
  * `/usr/local/etc/sngreprc`

Several ways to approach this functionality:

In #24  I have implemented an option to set call list display filter from command line using -F flag.
I *could implement* a logic to reverse the match if first caracter is `!` so you could start filtering OPTIONS messages:

    sngrep -F "!OPTIONS" port 5060

Anyway, this feature will be nice also for filtering positively. A flag for selecting the methods you're interested in and a possibility to reverse thas filter. Also, sngrep flags right now are simple getopts, so only single characters can be used.

Maybe something like:
 
    # Only show invites and registers
    sngrep -m INVITE,REGISTER port 5060

    # Show all methods but OPTIONS
    sngrep -M OPTIONS port 5060

I don't like too much using two different flags for the same functionality, so maybe only implement one and another flag to reverse the match..

**Comment by Kaian** [comment]
Another workaround.

Development branch `match_expression` can do this with regexps

    sngrep -iv "cseq: [0-9]+ options" port 5060

**Comment by ssinyagin** [comment]
it would actually be nice to have a CLI option to ignore OPTIONS and REGISTER packets, so that it would apply to the global capture. 

At the moment, if I press F and deselect OPTIONS and REGISTER, sngrep still shows me the old capture (in my case, it's a 1-hour packet dump with more than 2000 SIP requests, so I hit the capture.limit setting), just limiting the display, but not the memory footprint.

A CLI option would be useful if it would ignore those SIP requests while reading the capture, so that they don't affect the in-memory representation and the capture.limit setting.

**Comment by Kaian** [comment]
I see that It wouldn't be the most user friendly option, but with `match_expression` branch it could be attained via:

`sngrep -iv "cseq: [0-0]+ (options|register)" ...`

My flag suggestion (-m, -M) could be a bit misleading. 

Another possible solution: Move sngrep to getopts_long to allow multiple --ignore options, something like: 
`sngrep --ignore OPTIONS --ignore REGISTER -d any ....`

**Comment by ssinyagin** [comment]
basically OPTIONS and REGISTER are the most noisy packets, and the rest is actually fine to see in the list. Of course sometimes one needs to see that OPTIONS and registration are happening and are processed properly, so this really needs a user-friendly flag.

How about this:  a `-n` flag (or `-z`)  to disable noisy packets, and a setting in sngreprc which defines such noisy packets as OPTIONS,REGISTER.

**Comment by Kaian** [comment]
In fact, in most cases all packets could be considered noisy instead of INVITE. Presence Notifications, subscriptions to events, etc also seem quite noisy. If this would be true, it may be more useful an --invites flag.

**Comment by ssinyagin** [comment]
ha, you're actually right. A flag which display only real call sessions which start with an INVITE -- that will be perfect. And don;t forget to apply  it before reading the capture, so that the capture limit is not hit so quickly.

**Comment by Kaian** [comment]
I have added an option (`-c` or `--calls`) that **only loads** calls when its first message is an INVITE method. If not, the call structure won't be created and the call counter won't increase towards call limit option.

I have also added long versions of the other command line arguments, check `sngrep --help`

Now you can use:
`sngrep --calls --input file.pcap port 5060`

I know this is not what @SebastianThorn requested, but If it fits his needs I'll close this issue.

Cheers,

**Comment by SebastianThorn** [comment]
it does :+1:

**Comment by davidcsi** [comment]
> 

This is gold, thanks!
